services:
  express-app:
    build: .
    ports:
      - "3000:3000"  # Expose port 3000
    restart: unless-stopped  # Restart policy
    environment:
      - KAFKA_BROKER=kafka-broker:9092  # Connect via container name
    networks:
      - shared-kafka-net  # Same network as Kafka

networks:
  shared-kafka-net:
    name: kafka-net  # Name of the network
    external: true  # Reuse Kafka's network